changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - "**/*.test.{js,ts}"
  - "**/*.spec.{js,ts}"

defaultSemverRangePrefix: ""

enableGlobalCache: false

logFilters:
  - code: YN0013
    level: discard

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

packageExtensions:
  material-ui-popup-state@*:
    peerDependencies:
      "react-dom": "*"
  stylelint-config-recommended-scss@*:
    peerDependencies:
      "postcss": "*"
  stylelint-config-standard-scss@*:
    peerDependencies:
      "postcss": "*"

supportedArchitectures:
  cpu:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.0.0-rc.25.cjs
