x-default: &default
  deploy:
    restart_policy:
      condition: "${DOCKER_DEFAULT_RESTART_POLICY:-unless-stopped}"
  env_file:
    - .env

services:
  tempo:
    image: ghcr.io/sokaisolutions/tempo:latest
    volumes:
      - ./.env:/root/.env
  nextjs:
    <<: *default
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        - PORT=${PORT}
    image: ghcr.io/jacobjove/jacobjove:latest
    depends_on:
      - tempo
    ports:
      - ${PORT}:${PORT}
    environment:
      NEXTAUTH_URL_INTERNAL: "http://nextjs:${PORT}"
      NEXTAUTH_URL: "https://jacobjove.org"
      NODE_ENV: production

volumes:
  data: null
