services:
  cypress:
    environment:
      - CYPRESS_baseUrl=https://www.orega.org/

  nextjs:
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NEXTAUTH_URL: "https://www.orega.org/"
      NODE_ENV: production
