services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        - PORT=${PORT}
    image: ghcr.io/iacobfred/portfolio:latest
    # depends_on:
    #   - mongo
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    environment:
      MONGODB_HOST: mongo
      NEXTAUTH_URL_INTERNAL: "http://nextjs:${PORT}"
      NEXTAUTH_URL: "https://orega.org"
      NODE_ENV: production
    volumes:
      - ./.env:/app/.env

volumes:
  data: null
  postgres_data: null
