x-environment: &default-environment
    DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    ENABLE_OPEN_USER_REGISTRATION: "True"

x-depends_on: &default-depends_on
    - postgres
    - redis

services:
    migrate:
        image: glitchtip/glitchtip:latest
        depends_on: *default-depends_on
        command: "./manage.py migrate"
        env_file: .env
        environment: *default-environment
    postgres:
        image: postgres:14
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        restart: unless-stopped
        volumes:
            - pg_data:/var/lib/postgresql/data
    redis:
        image: redis
        restart: unless-stopped
        volumes:
            - data:/data
    # smtp:
    #     # TODO: https://github.com/namshi/docker-smtp
    #     image: namshi/smtp
    #     restart: unless-stopped
    #     expose:
    #         - "25"
    #     environment:
    #         GMAIL_USER: ${GMAIL_USER}
    #         GMAIL_PASSWORD: ${GMAIL_PASSWORD}
    web:
        image: glitchtip/glitchtip:latest
        depends_on: *default-depends_on
        ports:
            - "${PORT}:${PORT}"
        env_file: .env
        environment: *default-environment
        restart: unless-stopped
    worker:
        image: glitchtip/glitchtip:latest
        command: celery -A glitchtip worker -B -l INFO
        depends_on: *default-depends_on
        env_file: .env
        environment: *default-environment
        restart: unless-stopped

volumes:
  data: null
  pg_data: null
