# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: integration
on:
  pull_request:
    branches: [main]
    paths-ignore:
      - .gitignore
      - .github/**
      - "!.github/workflows/integration.yml"
      - .husky/**
      - .idea/**
      - .vscode/**
      - "**.md"
      - "**.rst"
  push:
    branches: [main]
    paths-ignore:
      - .gitignore
      - .github/**
      - "!.github/workflows/integration.yml"
      - .husky/**
      - .idea/**
      - .vscode/**
      - "**.md"
      - "**.rst"
  workflow_dispatch:
    inputs:
      jobs:
        description: Comma-separated list of names of jobs to trigger
        required: false
        default: build

env:
  ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
  AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
  AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
  AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MONGO_DB: ${{ secrets.MONGO_DB }}
  MONGO_HOST: mongo
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SHA: ${{ github.sha }}
  SMTP_USER: ${{ secrets.SMTP_USER }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      added-files: ${{ steps.changed-files.outputs.added_files }}
      deleted-files: ${{ steps.changed-files.outputs.deleted_files }}
      modified-files: ${{ steps.changed-files.outputs.modified_files }}
      all-changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v32.0.0
  build:
    name: Build image
    needs: changed-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app: portfolio
            port: 3000
          - app: blog
            port: 3003
        # app: ["blog", "portfolio"]
    environment: ${{ matrix.app }}
    if: github.actor != 'depbot'
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Generate .env file
        uses: iacobfred/generate-dotenv@v0.3.1
        with:
          output-path: apps/${{ matrix.app }}/.env
          template-paths: |
            apps/${{ matrix.app }}/.config/_.env
            apps/${{ matrix.app }}/.config/_.env.production
        env:
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
          AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
          AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
          AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }}
          PORT: ${{ matrix.port }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image with cache
        id: build_with_cache
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v3
        with:
          build-args: |
            APP_NAME=${{ matrix.app }}
            PORT=${{ matrix.port }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,scope=${{ matrix.app }},mode=max
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/iacobfred/${{ matrix.app }}:${{ github.sha }},ghcr.io/iacobfred/${{ matrix.app }}:latest
      - name: Build image without cache
        if: ${{ failure() && steps.build_with_cache.outcome == 'failure' }}
        uses: docker/build-push-action@v3
        with:
          build-args: |
            APP_NAME=${{ matrix.app }}
            PORT=${{ matrix.port }}
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,scope=${{ matrix.app }},mode=max
          tags: ghcr.io/iacobfred/${{ matrix.app }}:${{ github.sha }}
      - name: Run containers
        run: |
          cd apps/${{ matrix.app }}
          docker compose pull;
          docker compose up -d --no-build --wait || {
            docker compose logs nextjs;
            docker compose ps;
            exit 1;
          }
